import { Inter } from "next/font/google";
import "./globals.css";
import MainLayout from "@/components/layout/MainLayout";
import { headers } from "next/headers";
import MusicPlayer from "@/components/layout/MusicPlayer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  const heads = headers();
  const header_url = heads.get("x-url") || "";


  let unAuthUrl = ["/login", "/register"];
  let components = "";
  if (unAuthUrl.includes(header_url)) {
    components = <div>{children}</div>;
  } else {
    components = <MainLayout>{children}</MainLayout>;
  }
  return (
    <html lang="en">
      <body className={inter.className}>

        {components}
      <MusicPlayer />
      </body>
    </html>
  );
}
