import { Inter } from "next/font/google";
import "./globals.css";
import MainLayout from "@/components/layout/MainLayout";
import { headers } from "next/headers";
import MusicPlayer from "@/components/layout/MusicPlayer";
import { ToastContainer } from "react-toastify";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className={inter.className}>

        <MainLayout>{children}</MainLayout>
        <MusicPlayer />
        <ToastContainer position="top-right"

        />
      </body>
    </html>
  )
}
